#!/usr/bin/env python

from app.commands import Commands


def main():
    commands = Commands()

    while(True):
        try:
            command = input("> ")
            print (command)

        except (EOFError, KeyboardInterrupt):
            break

        if command in ('q', 'quit', 'x', 'exit'):
            break

        args = command.split(' ')
        method = args.pop(0)

        if not hasattr(commands, method):
            print ("*** Method not found")

        if method in dir(commands):
            kwargs = {}
            result = getattr(commands, method)(*args, **kwargs)


if __name__ == '__main__':
    main()
