#!/usr/bin/env python

from app import services


def main():
    while(True):
        try:
            command = input("> ")
            print (command)

        except EOFError:
            break

        if command in ('q', 'quit', 'x', 'exit'):
            break

        args = command.split(' ')
        method = args.pop(0)

        if not hasattr(services, method):
            print ("Method not found")

        if method in dir(services):
            kwargs = {}
            result = getattr(services, method)(*args, **kwargs)
            print (result)


if __name__ == '__main__':
    main()
